# require 'simplecov'
# SimpleCov.start
require_relative './stat_tracker'
require_relative './all_season_data'
require_relative './single_season_data'
require_relative './team'
require_relative './team_season'
require_relative './game'
require_relative './coach'
require 'csv'
require 'benchmark'